### ISSUE TITLE
Request -  Can you add git tags in the release process

### ISSUE THREAD

**Issue by euskadi31** [michaeltchapman/puppet-galera#44]
Hi,

We have a little request for the development process of your excellent puppet module we currently using. Can you use the release tags from git when you provide new version in github?

'Cause when we using on our env without this information we get all the modification since our last install and sometime it broke :D like today.

If you use a versioning naming, like in semver.org, we can rely on a precise one and make migration process to a new version with more security.

Thanks a lot for the time provided to the community

**Comment by michaeltchapman** [comment]
I thought I'd added a tag when I did the forge release, but clearly not. My bad!

**Comment by euskadi31** [comment]
Thanks ;)

**Comment by michaeltchapman** [comment]
There should now be an 0.0.1 tag. Enjoy.
