### ISSUE TITLE
So - I tried upgrading the module to use Percona 5.6...

### ISSUE THREAD

**Issue by Shoeler** [michaeltchapman/puppet-galera#62]
I changed my code similar to PR 61 ( #61 ) and all seems well.

Until it tries as a part of galera::init to run exec { "create ${::root_home}/.my.cnf" from what I can tell - which then calls mysql::root_password and its "remove install pass" resource.  Later in mysql::server::root_password, it then tries to set the root password (as I've passed in my manifest to the galera module) which seems to fail.

Here's the debug output from the puppet run below.  The way I fixed it is to do a manual password recovery except adding the --wsrep-new-cluster line (per http://dev.mysql.com/doc/refman/5.6/en/resetting-permissions.html) to the password that I told the galera manifest I wanted to use.  Puppet's next run then does all the other DB creation and stuff I told it to and all seems happy.  This only breaks on the initial puppet run for a node.  

So it seems that the root password is not being set as it would seem to be.

A snippet from my mysql manifest:

class { 'galera':
    galera_servers                    => ['10.0.0.2,10.0.0.3,10.0.0.4'],
    galera_master                     => 'firstnode.example.com',
    local_ip                          => $::ipaddress_eth0,
    root_password                     => 'MyPassword', 
    configure_repo                    => false, 
    configure_firewall                => true,
    wsrep_sst_method                  => 'xtrabackup-v2',
    validate_connection               => false,
    status_check                      => false,
  }

First run output:

Debug: Executing: '/usr/bin/dpkg-query -W --showformat '${Status} ${Package} ${Version}\n' percona-xtrabackup'
Debug: Executing: '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install percona-xtrabackup'
Notice: /Stage[main]/Galera/Package[percona-xtrabackup]/ensure: created
Debug: /Package[percona-xtrabackup]: The container Class[Galera] will propagate my refresh event
Debug: Executing: '/usr/bin/dpkg-query -W --showformat '${Status} ${Package} ${Version}\n' percona-xtradb-cluster-galera-3.x'
Debug: Executing: '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install percona-xtradb-cluster-galera-3.x'
Notice: /Stage[main]/Galera/Package[percona-xtradb-cluster-galera-3.x]/ensure: created
Debug: /Package[percona-xtradb-cluster-galera-3.x]: The container Class[Galera] will propagate my refresh event
Debug: Executing: '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install percona-xtradb-cluster-server-5.6'
Notice: /Stage[main]/Mysql::Server::Install/Package[mysql-server]/ensure: created
Info: /Package[mysql-server]: Scheduling refresh of Exec[clean_up_ubuntu]
Debug: /Package[mysql-server]: The container Class[Mysql::Server::Install] will propagate my refresh event
Debug: Class[Mysql::Server::Install]: The container Stage[main] will propagate my refresh event
Debug: Exec[clean_up_ubuntu](provider=posix): Executing 'service mysql stop'
Debug: Executing: 'service mysql stop'
Notice: /Stage[main]/Galera::Debian/Exec[clean_up_ubuntu]: Triggered 'refresh' from 1 events
Debug: /Stage[main]/Galera::Debian/Exec[clean_up_ubuntu]: The container Class[Galera::Debian] will propagate my refresh event
Notice: /Stage[main]/Mysql::Server::Config/File[mysql-config-file]/ensure: defined content as '{md5}6bd09508c53bb37b90ad3c08f3969a92'
Debug: /Stage[main]/Mysql::Server::Config/File[mysql-config-file]: The container Class[Mysql::Server::Config] will propagate my refresh event
Debug: Class[Mysql::Server::Config]: The container Stage[main] will propagate my refresh event
Debug: Exec[bootstrap_galera_cluster](provider=shell): Executing check '["/bin/sh", "-c", "nmap -p 4567 10.0.0.1 10.0.0.2 10.0.0.3 | grep -q '4567/tcp open'"]'
Debug: Executing: '/bin/sh -c nmap -p 4567 10.0.0.1 10.0.0.2 10.0.0.3 | grep -q '4567/tcp open''
Debug: Exec[bootstrap_galera_cluster](provider=shell): Executing '["/bin/sh", "-c", "/etc/init.d/mysql bootstrap-pxc"]'
Debug: Executing: '/bin/sh -c /etc/init.d/mysql bootstrap-pxc'
Notice: /Stage[main]/Galera/Exec[bootstrap_galera_cluster]/returns: executed successfully
Debug: /Stage[main]/Galera/Exec[bootstrap_galera_cluster]: The container Class[Galera] will propagate my refresh event
Notice: /Stage[main]/Mysql::Server::Service/File[/var/log/mysql/error.log]/group: group changed 'adm' to 'mysql'
Debug: /Stage[main]/Mysql::Server::Service/File[/var/log/mysql/error.log]: The container Class[Mysql::Server::Service] will propagate my refresh event
Debug: Service[mysqld](provider=upstart): Could not find mysql.conf in /etc/init
Debug: Service[mysqld](provider=upstart): Could not find mysql.conf in /etc/init.d
Debug: Service[mysqld](provider=upstart): Could not find mysql in /etc/init
Debug: Executing: '/etc/init.d/mysql status'
Debug: Exec[create /root/.my.cnf](provider=posix): Executing check '/usr/bin/mysql --user=root --password=pa$$word -e 'select count(1);''
Debug: Executing: '/usr/bin/mysql --user=root --password=pa$$word -e 'select count(1);''
Debug: /Stage[main]/Galera/Exec[create /root/.my.cnf]/onlyif: Warning: Using a password on the command line interface can be insecure.
Debug: /Stage[main]/Galera/Exec[create /root/.my.cnf]/onlyif: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
Debug: Class[Galera]: The container Stage[main] will propagate my refresh event
Debug: Class[Mysql::Server::Service]: The container Stage[main] will propagate my refresh event
Debug: Exec[remove install pass](provider=posix): Executing check 'test -f /.mysql_secret'
Debug: Executing: 'test -f /.mysql_secret'
Debug: Prefetching mysql resources for mysql_user
Debug: Executing: '/usr/bin/mysql --defaults-extra-file=/root/.my.cnf -NBe SELECT CONCAT(User, '@',Host) AS User FROM mysql.user'
Debug: Storing state
Debug: Stored state in 0.04 seconds
Error: Failed to apply catalog: Execution of '/usr/bin/mysql --defaults-extra-file=/root/.my.cnf -NBe SELECT CONCAT(User, '@',Host) AS User FROM mysql.user' returned 1: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by michaeltchapman** [comment]
What base OS is this on? I'll try to reproduce it.

**Comment by Shoeler** [comment]
ubuntu 14.04 64-bit.  Thanks!

**Comment by michaeltchapman** [comment]
Is that your actual password? Try using one without '$' in it - it might be trying to do substitutions in the shell. I also get issues with 'pa$$word' but with 'password' it works fine.

**Comment by Shoeler** [comment]
That's not my actual password - but I'll check to see if what you're saying changes it!

**Comment by Shoeler** [comment]
Changing the password to a purely alphanumeric one did not affect the outcome, sadly :(

**Comment by Shoeler** [comment]
Hey - I think I fixed it.  I was testing on the same server over and over again and it wasn't updating the /root/.my.cnf file like it should have been.  I uninstalled everything and deleted that file and poof - works.

**Comment by michaeltchapman** [comment]
Glad you got it working :)
