### ISSUE TITLE
Bootstrap dependency

### ISSUE THREAD

**Issue by jdecalog** [michaeltchapman/puppet-galera#65]
Hello,

I've got a problem with bootstraping the cluster.
The dependency on Class['mysql::server::installdb'] is not found.
Where should it be declared?

And secondly, on Debian jessie the bootstrap command 
`service mysql start --wsrep_cluster_address=gcomm://`
doesn't work
I have to use 
 `/etc/init.d/mysql start --wsrep_cluster_address=gcomm://`
It could be helpful to set this command within the parameters

Thanks

**Comment by michaeltchapman** [comment]
For the first issue, it's part of the mysql module, here: https://github.com/puppetlabs/puppetlabs-mysql/blob/master/manifests/server/installdb.pp

It looks like it was only added fairly recently so I'll bump the required version of puppet-mysql.

For the second, please feel free to submit a change with working config for jessie - it isn't tested at the moment.

 - Michael
