### ISSUE TITLE
Dependency cycle with recent commit

### ISSUE THREAD

**Issue by mjblack** [michaeltchapman/puppet-galera#74]
It looks like a recent commit (a9c6bce94dcb3371a63e92a55744090c213a1e55)  has introduced a circular dependency cycle.

```
Error: Failed to apply catalog: Found 1 dependency cycle:
(File[/etc/mysql/conf.d] => Class[Mysql::Server::Config] => Package[rsync] => Class[Mysql::Server::Install] => Package[mysql-server] => Class[Mysql::Server::Install] => Class[Mysql::Server::Config] => File[/etc/mysql/conf.d])
```

**Comment by michaeltchapman** [comment]
which version of puppet-mysql are you using?

**Comment by claudekenni** [comment]
I have the same issue
`
root@puppet:/etc/puppetlabs# /opt/puppetlabs/puppet/bin/puppet module install michaeltchapman-galera
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└─┬ michaeltchapman-galera (v0.4.0)
  ├── puppetlabs-apt (v2.2.2)
  ├── puppetlabs-firewall (v1.8.1)
  ├── puppetlabs-mysql (v3.8.0)
  ├── puppetlabs-stdlib (v4.12.0)
  └── puppetlabs-xinetd (v2.0.0)
`

**Comment by michaeltchapman** [comment]
@claudekenni try the master branch.

**Comment by mjblack** [comment]
```
$ git describe
3.6.2-2-g10b873c
```

**Comment by michaeltchapman** [comment]
I've tested with both cent 7 and trusty 64 using master branch of this module + master branch of the mysql module, and those work for me. You'll need to provide more information about your environment if that does not work for you.

**Comment by redcricket** [comment]
I am find a dependency cycle error too: http://stackoverflow.com/questions/38491667/getting-dependency-cycle-when-using-michaeltchapman-galera

**Comment by redcricket** [comment]
I just tried the master branch and the dependency cycle error is corrected.

**Comment by michaeltchapman** [comment]
@redcricket thanks for checking. I've pushed a new version of this module (0.0.6) to the forge that requires puppetlabs-mysql 3.8.0, so I think forge installs will work now as well.
